version: "3.3"
services:
  core:
    build:
      context: ./
      dockerfile: ./packages/core/Dockerfile.dev
    volumes:
      - "./packages/core:/app/packages/core"
    env_file:
      - ./packages/core/.env
    ports:
      - "5002:5002"
    depends_on:
      - "mongo"
    networks:
      - mongo-network

  mongo:
    image: "mongo"
    restart: always
    volumes:
      - db:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongo-network

  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
      - "1234:1234"
    environment:
      - HOST=0.0.0.0
    networks:
      - mongo-network

volumes:
  db:
    driver: local

networks:
  mongo-network:
    driver: bridge
